version: "3.4"

services:

  dynamic_dns:
    image: couling/dynamic-dns-aws:latest
    restart: always
    volumes:
      - ./etc/dynamic_dns.yaml:/etc/dynamic-dns-aws/dynamic-dns.yaml
      - $HOME/.aws/:/root/.aws

